version: '2'

services:
  drupal:
    image: servinube/drupal
    volumes:
      - ./app:/var/www
      - ./data/private:/var/www/private
      - ./data/default:/var/www/web/sites/default
    environment:
      VIRTUAL_HOST: localhost
      DRUPAL_URL: http://localhost
      DRUPAL_ENV: dev
    links:
      - mysql
    network_mode: bridge

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: cbiYudbJ9RLOnLdI
      MYSQL_USER: drupal
      MYSQL_PASSWORD: xQcmVQvI0YyHLqQX
      MYSQL_DATABASE: drupal8
    volumes:
      - ./data/mysql:/var/lib/mysql
    network_mode: bridge

  composer:
    extends:
      service: composer
      file: ~/Projects/docker-compose.yml
    volumes:
     - ./app:/app
